api/urls.py
from django.urls import path
from rest_framework.authtoken import views as drf_views

from . import views

urlpatterns = [
    path('token/', drf_views.obtain_auth_token),
    path('cv/', views.CVListAPIView.as_view()),
]

cv_generator/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('cvAdmin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('api/',include('api.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns=[       
        path('', views.DashboardView.as_view(), name='index'),
        
        # accounts
        path('accounts/login/', views.LoginPageView.as_view(), name='login'),
        path('accounts/logout/', views.LogoutView.as_view(), name='logout'),

        # user crud
        path('users/', views.UserListView.as_view(), name='users-list'),
        path('users/create', views.UserCreateView.as_view(), name='users-create'),
        path('users/<int:pk>/update', views.UserUpdateView.as_view(), name='users-update'),
        path('users/<int:pk>/status', views.UserStatusView.as_view(), name='users-status'),

        #CVS CRUD
        path('cvs/', views.CurriculumVitaeListView.as_view(), name='cvs-list'),
        path('cv/<int:pk>/detail/', views.CurriculumVitaeDetailView.as_view(), name='cv-detail'),
]

dashboard/models.py
from datetime import date, datetime
from urllib.parse import parse_qs, urlsplit

from django.apps import apps
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.core.validators import FileExtensionValidator
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.shortcuts import get_object_or_404, reverse
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.html import strip_tags

from .utils import *
from .validators import *

GENDER = (
    (1,'Male'),
    (2,'Female'),
    (3,'Others'),
)


CURRENTLY_WORKING_TYPE = (
    ('Yes','Yes'),
    ('No','No'),
)

def get_candidate(user):
    try:
        return user.candidate
    except:
        pass
    return None


class DateTimeModel(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True,
        auto_now=False,
    )
    updated_at = models.DateTimeField(
        auto_now_add=False,
        auto_now=True,
    )
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True

    def delete(self):
        self.deleted_at = timezone.now()
        super().save()


class Skill(models.Model):
    name = models.CharField(max_length=254, unique=True)

    class Meta:
        ordering = ['-id']
        verbose_name = "Skill"
        verbose_name_plural = "Skills"

    def __str__(self):
        return self.name

class Candidate(User, DateTimeModel):
    gender = models.IntegerField(choices = GENDER,blank = False,null= True)
    dob = models.DateField(blank = False,null = True)
    is_verified = models.BooleanField(default = False)
    mobile_number = models.CharField(max_length=13,blank = False,null= True)
    address = models.CharField(max_length = 120,blank = False, null= True)
    skills = models.ManyToManyField(Skill,related_name='candidates')
    profile_image = models.FileField(null=True, blank=True, validators=[FileExtensionValidator(allowed_extensions=['png','jpg','jpeg'])])
    about_me = models.TextField(blank=True, null=True)
    
    class Meta:
        ordering = ['-id']
        verbose_name = "Candidate"
        verbose_name_plural = "Candidates"

    def __str__(self):
        return self.username

    @property
    def name(self):
        return "{0} {1} ".format(self.first_name,self.last_name)

    def get_photo(self):
        try:
            return self.profile_image.url
        except:
            return self.get_avatar()

    def get_avatar(self):
        url="https://ui-avatars.com/api/?background=0D8ABC&color=fff&name={0}+{1}&size=256".format(self.first_name,self.last_name)
        return url

    @property
    def get_skills(self):
        return self.skills.all

    @property
    def get_educations(self):
        return self.educational_qualifications.filter(deleted_at__isnull=True)


class EducationalQualification(DateTimeModel):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='educational_qualifications')
    degree = models.CharField(max_length=100)
    name_of_institute = models.CharField(max_length=200)
    university = models.CharField(max_length=200)
    location = models.CharField(max_length=100)
    started_year = models.CharField(max_length=10)
    passed_year = models.CharField(max_length=10)
    description = models.TextField()

    class Meta:
        verbose_name = "Educational Qualification"
        verbose_name_plural = "Educational Qualifications"
        ordering = ["-id"]

    def __str__(self):
        return self.candidate.username


class WorkExperience(DateTimeModel):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='work_experiences')
    job_title = models.CharField(max_length=250)
    organization = models.CharField(max_length=250)
    is_working = models.IntegerField(choices=CURRENTLY_WORKING_TYPE , null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    job_description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Work Experience"
        verbose_name_plural = "Work Experiences"
        ordering = ["-id"]

    def __str__(self):
        return self.candidate.username

    
class CurriculumVitae(DateTimeModel):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='cvs')
    cv_generated = models.FileField()

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.candidate.username

dashboard/forms.py
from django.contrib.auth.models import User
from django import forms
from django.utils.html import mark_safe

from .mixins import FormControlMixin 


class SignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'required': 'true',
        'placeholder': 'Password *'}))
    
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'required': 'true',
        'placeholder': 'Retype Password *'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'confirm_password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

        self.fields['first_name'].widget.attrs.update({'placeholder':'First Name'})
        self.fields['last_name'].widget.attrs.update({'placeholder':'Last Name'})
        self.fields['username'].widget.attrs.update({'placeholder':'Username'})
        self.fields['email'].label = "Email"
        self.fields['password'].label = "Password"
        self.fields['confirm_password'].label = "Confirm Password"

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if not confirm_password:
            raise forms.ValidationError("You must confirm your password")
        if password != confirm_password:
            raise forms.ValidationError("Your passwords do not match")

        return confirm_password

    def clean_email(self):
        data = self.cleaned_data.get('email')
        if not data:
            raise forms.ValidationError("Email cannot be Empty")
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError(mark_safe("<span style='color: red;'>User with this email already exists</span>"))

        # Always return the cleaned data, whether you have changed it or
        # not.
        return data


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder':  'Username'}))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder':  'Password'}))

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = User.objects.filter(username=username, is_active=True).first()
        if user == None or not user.check_password(password):
            raise forms.ValidationError("Incorrect username or password")
        return self.cleaned_data


class UserForm(FormControlMixin, forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("User with this email address already exists")
        
        return email

dashboard/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import  reverse_lazy
from django.views.generic import View, TemplateView, FormView, ListView, CreateView, UpdateView
from django.db.models import Count

from .forms import (
    LoginForm, 
    UserForm
)
from .mixins import SuperAdminRequiredMixin
from .models import * 

User = get_user_model()


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/layouts/home.html"


# Login Logout Views
class LoginPageView(FormView):
    form_class = LoginForm
    template_name = "dashboard/auth/login.html"

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)

        # Remember me
        if self.request.POST.get('remember', None) == None:
            self.request.session.set_expiry(0)

        login(self.request, user)

        if 'next' in self.request.GET:
            return redirect(self.request.GET.get('next'))
        return redirect('dashboard:index')
        

class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('dashboard:login')


# User CRUD
class UserListView(SuperAdminRequiredMixin, ListView):
    model = User
    template_name = "dashboard/users/list.html"
    paginate_by = 100

    def get_queryset(self):
        return super().get_queryset().annotate(cv_count=Count('candidate__cvs', distinct=True)).exclude(username=self.request.user)


class UserCreateView(SuperAdminRequiredMixin, SuccessMessageMixin, CreateView):
    form_class= UserForm
    success_message = "User Created Successfully"
    success_url = reverse_lazy('dashboard:users-list')
    template_name = "dashboard/users/form.html"
    

class UserUpdateView(SuperAdminRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = UserForm
    model = User
    success_message = "User Updated Successfully"
    success_url = reverse_lazy('dashboard:users-list')
    template_name = "dashboard/users/form.html"


class UserStatusView(SuperAdminRequiredMixin, SuccessMessageMixin, View):
    model = User
    success_message = "User's Status Has Been Changed"
    success_url = reverse_lazy('dashboard:users-list')

    def get(self, request, *args, **kwargs):
        user_id = self.kwargs.get('pk')
        if user_id:
            account = User.objects.filter(id=user_id).first()
            account.is_active = not account.is_active
            account.save(update_fields=['is_active'])
        return redirect(self.success_url)


class CurriculumVitaeListView(SuperAdminRequiredMixin, ListView):
    model = CurriculumVitae
    template_name = "dashboard/cvs/list.html"
    paginate_by = 100

    def get_queryset(self):
        return super().get_queryset().filter(deleted_at__isnull=True)


class CurriculumVitaeDetailView(SuperAdminRequiredMixin, ListView):
    model = CurriculumVitae
    template_name = "dashboard/cvs/detail.html"
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['candidate'] = get_candidate(self.request.user) 
        return context

    

dashboard/templates/dashboard/users/form.html
{% extends "dashboard/layouts/home.html" %}

{% load static %}

{% block title %} User {% endblock %}

{% block content %}
<div class="container-fluid page__container">
    <div class="card card-form form-header-layout">
        <h1 style="padding: 27px !important;"> User </h1>
        <div class="row no-gutters" style="border-top: 1px solid #EFEFEF">
            <div class="col-lg-12 card-form__body card-body pomelo-form-caard" style="background:none !important;">
                <form method="post" action="" enctype="multipart/form-data" autocomplete="off">
                    
                    {% csrf_token %}

                    {% for field in form %}
                    <div class="form-group" >
                        <label>{{ field.label }}{% if field.field.required %}* {% endif %}</label>
                        {{ field }}
                        <span style="color:red;">{{ field.errors|striptags|safe }}</span>
                    </div>
                    {% endfor %}    

                    <button type="submit" class="btn btn-primary"><i class="fa fa-check"></i> Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

dashboard/templates/dashboard/users/list.html
{% extends "dashboard/layouts/home.html" %}

{% load static %}

{% block title %} Users {% endblock %}

{% block subtitle %} Users {% endblock %}

{% block content %}

<div class="container-fluid page__container">
    <div class="card document-card">
        <div class="row mb-4 mt-4 mr-2">
            <div class="col-md-12">
                <div style="text-align: right">
                    <a href="{% url 'dashboard:users-create' %}" class="btn btn-outline-primary">
                        <i class="fa fa-plus"></i>&nbsp; Add User
                    </a>
                </div>
            </div>
        </div>
        <div class="row ml-2 mr-2 mb-2 mt-2">
            <div class="col-sm-12 document-table-space">
                <table class="table  w-full no-footer" role="grid" id="userstable">
                    <thead class="table-space-top-bottom">
                        <tr role="row">
                            <th>S.N</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th>Number of CV Generated</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for users in object_list %}
                        <tr>
                            <td>{{ page_obj.start_index|add:forloop.counter0 }}</td>
                            <td>{{ users.username }}</td>
                            <td>{{ users.email }}</td>
                            <td>{% if users.is_active == True %} <span class="badge badge-success"> Active </span>
                                {% else %} <span class="badge badge-danger"> In Active </span> {% endif %}</td>
                            <td>{{ users.cv_count }}</td>
                            <td>
                                <div class="btn-group" role="group" style="margin:auto;">
                                    &nbsp;
                                    <a href="{% url 'dashboard:users-update' users.id %}"
                                        class="btn-sm btn btn-info btn-success-space" data-toggle="tooltip"
                                        data-original-title='Modify'>
                                        <i class="fa fa-pencil-alt"></i>
                                    </a>
                                    {% if request.user.is_superuser %}
                                    <a href="{% url 'dashboard:users-status' users.id %}" data-toggle="tooltip"
                                        {% if users.is_active == True %} class="btn-sm btn btn-danger user-deactivate"
                                        data-original-title='Deactivate' {% else %}
                                        class="btn-sm btn btn-success user-activate" data-original-title='Activate'
                                        {% endif %}>
                                        {% if users.is_active == True %}
                                        <i class="fas fa-ban"></i>
                                        {% else %}
                                        <i class="fas fa-check"></i>
                                        {% endif %}
                                    </a>
                                    {% endif %}
                                </div>
                            </td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
                {% include 'dashboard/layouts/pagination.html' %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function () {
        $('#userstable').DataTable();
    })
    // password reset link
    $('body').on('click', '.password-reset', function (e) {
        e.preventDefault();
        Swal.fire({
            title: 'Are you sure?',
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Password Reset It!'
        }).then((result) => {
            if (result.value) {
                window.location.href = $(this).attr('href');
            }
        })
    });

    // user activate 
    $('body').on('click', '.user-activate', function (e) {
        e.preventDefault();
        Swal.fire({
            title: 'Are you sure you want to activate this user?',
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Activate It!'
        }).then((result) => {
            if (result.value) {
                window.location.href = $(this).attr('href');
            }
        })
    });

    // user deactivate 
    $('body').on('click', '.user-deactivate', function (e) {
        e.preventDefault();
        Swal.fire({
            title: 'Are you sure you want to deactivate this user?',
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Deactivate It!'
        }).then((result) => {
            if (result.value) {
                window.location.href = $(this).attr('href');
            }
        })
    });
</script>
{% endblock %}