api/urls.py
from django.urls import path
from rest_framework.authtoken import views as drf_views

from . import views

urlpatterns = [
    path('token/', drf_views.obtain_auth_token),
    path('cv/', views.CVListAPIView.as_view()),
]

cv_generator/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('cvAdmin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('api/',include('api.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns=[       
        path('', views.DashboardView.as_view(), name='index'),
        
        # accounts
        path('accounts/login/', views.LoginPageView.as_view(), name='login'),
        path('accounts/logout/', views.LogoutView.as_view(), name='logout'),

        # user crud
        path('users/', views.UserListView.as_view(), name='users-list'),
        path('users/create', views.UserCreateView.as_view(), name='users-create'),
        path('users/<int:pk>/update', views.UserUpdateView.as_view(), name='users-update'),
        path('users/<int:pk>/status', views.UserStatusView.as_view(), name='users-status'),

        #CVS CRUD
        path('cvs/', views.CurriculumVitaeListView.as_view(), name='cvs-list'),
        path('cv/<int:pk>/detail/', views.CurriculumVitaeDetailView.as_view(), name='cv-detail'),
]

frontend/urls.py
from django.urls import path

from .views import *

app_name = 'frontend'

urlpatterns = [
    #HomeView
    path('', HomeView.as_view(), name='home'),

    #Accounts Login, Logout and Register
    path('login/', SigninView.as_view(), name='login'),
    path('logout/',LogoutView.as_view(), name = 'logout'),
    path('register/',SignupView.as_view(), name = 'signup'),

    #Email Confirmations 
    path('resend/token/', SendTokenView.as_view(), name = 'send_token'),
    path('activate/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', activate, name='activate_account'),

    #Candidates Profile Detail updates
    path('candidate/<username>/', CandidateUpdateView.as_view(), name='candidate_update'),
    path('personaldetails/<int:pk>/', CandidateProfileDetailUpdateView.as_view(),  name='candidate_personal_detail_update'),
    
    # Candidate Photo Update
    path('candidate/photo/update/', CandidatePhotoUpdateView.as_view(), name='candidate_photo_update'),

    # Candidate CV Update and Download
    path('cv/edit/<username>/', CandidateEditCVTemplateView.as_view(), name='candidate_cv_update'),
    path('download/cv/', CandidateCVDownloadTemplateView.as_view(), name='candidate_cv_download'),
    # path('generate-cv/<int:pk>/', GenerateCVPDFView.as_view(), name="generate_cv_pdf"),

    # Candidate Education CRUD
    path('education/create/', CandidateEducationCreateView.as_view(), name='candidate_education_create'),
    path('education/<int:pk>/', CandidateEducationUpdateview.as_view(), name='candidate_education_update'),
    path('education/<int:pk>/delete/',CandidateEducationDeleteView.as_view(), name='candidate_education_delete'),
    path('aboutme/<int:pk>/', CandidateAboutMeUpdateView.as_view(), name='candidate_aboutme_update'),

    #Candidate Experience CRUD
    path('experience/<int:pk>/', CandidateExperienceUpdateView.as_view(),  name='candidate_experience_update'),
    path('experience/create/', CandidateExperienceCreateView.as_view(), name='candidate_experience_create'),
    path('experience/<int:pk>/delete/',CandidateExperienceDeleteView.as_view(), name = 'candidate_experience_delete'),


]

dashboard/models.py
from datetime import date, datetime
from urllib.parse import parse_qs, urlsplit

from django.apps import apps
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.core.validators import FileExtensionValidator
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.shortcuts import get_object_or_404, reverse
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.html import strip_tags

from .utils import *
from .validators import *

GENDER = (
    (1,'Male'),
    (2,'Female'),
    (3,'Others'),
)


CURRENTLY_WORKING_TYPE = (
    ('Yes','Yes'),
    ('No','No'),
)

def get_candidate(user):
    try:
        return user.candidate
    except:
        pass
    return None


class DateTimeModel(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True,
        auto_now=False,
    )
    updated_at = models.DateTimeField(
        auto_now_add=False,
        auto_now=True,
    )
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True

    def delete(self):
        self.deleted_at = timezone.now()
        super().save()


class Skill(models.Model):
    name = models.CharField(max_length=254, unique=True)

    class Meta:
        ordering = ['-id']
        verbose_name = "Skill"
        verbose_name_plural = "Skills"

    def __str__(self):
        return self.name

class Candidate(User, DateTimeModel):
    gender = models.IntegerField(choices = GENDER,blank = False,null= True)
    dob = models.DateField(blank = False,null = True)
    is_verified = models.BooleanField(default = False)
    mobile_number = models.CharField(max_length=13,blank = False,null= True)
    address = models.CharField(max_length = 120,blank = False, null= True)
    skills = models.ManyToManyField(Skill,related_name='candidates')
    profile_image = models.FileField(null=True, blank=True, validators=[FileExtensionValidator(allowed_extensions=['png','jpg','jpeg'])])
    about_me = models.TextField(blank=True, null=True)
    
    class Meta:
        ordering = ['-id']
        verbose_name = "Candidate"
        verbose_name_plural = "Candidates"

    def __str__(self):
        return self.username

    @property
    def name(self):
        return "{0} {1} ".format(self.first_name,self.last_name)

    def get_photo(self):
        try:
            return self.profile_image.url
        except:
            return self.get_avatar()

    def get_avatar(self):
        url="https://ui-avatars.com/api/?background=0D8ABC&color=fff&name={0}+{1}&size=256".format(self.first_name,self.last_name)
        return url

    @property
    def get_skills(self):
        return self.skills.all

    @property
    def get_educations(self):
        return self.educational_qualifications.filter(deleted_at__isnull=True)


class EducationalQualification(DateTimeModel):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='educational_qualifications')
    degree = models.CharField(max_length=100)
    name_of_institute = models.CharField(max_length=200)
    university = models.CharField(max_length=200)
    location = models.CharField(max_length=100)
    started_year = models.CharField(max_length=10)
    passed_year = models.CharField(max_length=10)
    description = models.TextField()

    class Meta:
        verbose_name = "Educational Qualification"
        verbose_name_plural = "Educational Qualifications"
        ordering = ["-id"]

    def __str__(self):
        return self.candidate.username


class WorkExperience(DateTimeModel):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='work_experiences')
    job_title = models.CharField(max_length=250)
    organization = models.CharField(max_length=250)
    is_working = models.IntegerField(choices=CURRENTLY_WORKING_TYPE , null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    job_description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Work Experience"
        verbose_name_plural = "Work Experiences"
        ordering = ["-id"]

    def __str__(self):
        return self.candidate.username

    
class CurriculumVitae(DateTimeModel):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='cvs')
    cv_generated = models.FileField()

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.candidate.username

frontend/models.py
from django.db import models

# Create your models here.

dashboard/forms.py
from django.contrib.auth.models import User
from django import forms
from django.utils.html import mark_safe

from .mixins import FormControlMixin 


class SignUpForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'required': 'true',
        'placeholder': 'Password *'}))
    
    confirm_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'required': 'true',
        'placeholder': 'Retype Password *'}))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password', 'confirm_password')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

        self.fields['first_name'].widget.attrs.update({'placeholder':'First Name'})
        self.fields['last_name'].widget.attrs.update({'placeholder':'Last Name'})
        self.fields['username'].widget.attrs.update({'placeholder':'Username'})
        self.fields['email'].label = "Email"
        self.fields['password'].label = "Password"
        self.fields['confirm_password'].label = "Confirm Password"

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')

        if not confirm_password:
            raise forms.ValidationError("You must confirm your password")
        if password != confirm_password:
            raise forms.ValidationError("Your passwords do not match")

        return confirm_password

    def clean_email(self):
        data = self.cleaned_data.get('email')
        if not data:
            raise forms.ValidationError("Email cannot be Empty")
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError(mark_safe("<span style='color: red;'>User with this email already exists</span>"))

        # Always return the cleaned data, whether you have changed it or
        # not.
        return data


class LoginForm(forms.Form):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder':  'Username'}))
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'placeholder':  'Password'}))

    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = User.objects.filter(username=username, is_active=True).first()
        if user == None or not user.check_password(password):
            raise forms.ValidationError("Incorrect username or password")
        return self.cleaned_data


class UserForm(FormControlMixin, forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'email']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exclude(pk=self.instance.pk).exists():
            raise forms.ValidationError("User with this email address already exists")
        
        return email

dashboard/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import redirect
from django.urls import  reverse_lazy
from django.views.generic import View, TemplateView, FormView, ListView, CreateView, UpdateView
from django.db.models import Count

from .forms import (
    LoginForm, 
    UserForm
)
from .mixins import SuperAdminRequiredMixin
from .models import * 

User = get_user_model()


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/layouts/home.html"


# Login Logout Views
class LoginPageView(FormView):
    form_class = LoginForm
    template_name = "dashboard/auth/login.html"

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)

        # Remember me
        if self.request.POST.get('remember', None) == None:
            self.request.session.set_expiry(0)

        login(self.request, user)

        if 'next' in self.request.GET:
            return redirect(self.request.GET.get('next'))
        return redirect('dashboard:index')
        

class LogoutView(View):
    def get(self, request, *args, **kwargs):
        logout(request)
        return redirect('dashboard:login')


# User CRUD
class UserListView(SuperAdminRequiredMixin, ListView):
    model = User
    template_name = "dashboard/users/list.html"
    paginate_by = 100

    def get_queryset(self):
        return super().get_queryset().annotate(cv_count=Count('candidate__cvs', distinct=True)).exclude(username=self.request.user)


class UserCreateView(SuperAdminRequiredMixin, SuccessMessageMixin, CreateView):
    form_class= UserForm
    success_message = "User Created Successfully"
    success_url = reverse_lazy('dashboard:users-list')
    template_name = "dashboard/users/form.html"
    

class UserUpdateView(SuperAdminRequiredMixin, SuccessMessageMixin, UpdateView):
    form_class = UserForm
    model = User
    success_message = "User Updated Successfully"
    success_url = reverse_lazy('dashboard:users-list')
    template_name = "dashboard/users/form.html"


class UserStatusView(SuperAdminRequiredMixin, SuccessMessageMixin, View):
    model = User
    success_message = "User's Status Has Been Changed"
    success_url = reverse_lazy('dashboard:users-list')

    def get(self, request, *args, **kwargs):
        user_id = self.kwargs.get('pk')
        if user_id:
            account = User.objects.filter(id=user_id).first()
            account.is_active = not account.is_active
            account.save(update_fields=['is_active'])
        return redirect(self.success_url)


class CurriculumVitaeListView(SuperAdminRequiredMixin, ListView):
    model = CurriculumVitae
    template_name = "dashboard/cvs/list.html"
    paginate_by = 100

    def get_queryset(self):
        return super().get_queryset().filter(deleted_at__isnull=True)


class CurriculumVitaeDetailView(SuperAdminRequiredMixin, ListView):
    model = CurriculumVitae
    template_name = "dashboard/cvs/detail.html"
    
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['candidate'] = get_candidate(self.request.user) 
        return context

    

frontend/templates/frontend/candidates/dashboard/profile_view.html
{% extends 'candidate/dashboard/dashboard.html'%}
{% block title %}Candidate profile{% endblock %}
{% block head %}{% endblock %}
{% load static %}


{% block dashboard %}
<div class="dashboard-content-wrapper dashboard-form">
  {% comment %}
  <div class="skill-and-profile dashboard-section">

    <div class="skill">
      <!-- Modal -->
    </div>
    <div class="social-profile">
      <a href="{% url 'frontend:candidate_update' request.user.candidate.username %}"
        class="btn btn-primary edit-button">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
          stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
          class="feather feather-edit-2">
          <polygon points="16 3 21 8 8 21 3 21 3 16 16 3"></polygon>
        </svg>
      </a>
    </div>
  </div>
  {% endcomment %}

  <form action="" method="POST" class="dashboard-form job-post-form">
    {% csrf_token %}
    <div class="dashboard-section upload-profile-photo">
      <div class="update-photo">
        <img class="a" src="{{ candidate.profile_image.url }}" alt="">
      </div>
      <div class="file-upload">
        <input class="file-input update-basic" data-toggle="modal" name="profile_image"
          data-url="{% url 'frontend:candidate_photo_update' %}" data-target="#MyModal2">Change Photo
      </div>
    </div>
  </form>

  {% comment %}
  <img src="{{ candidate.profile_image.url }}" style="width:200px;height:200px;">
  <br>
  <br>
  <br>
  <br>
  {% endcomment %}

  <div class="dashboard-section basic-info-input">
    <h4><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
        stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
        class="feather feather-user-check">
        <path d="M16 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
        <circle cx="8.5" cy="7" r="4"></circle>
        <polyline points="17 11 19 13 23 9"></polyline>
      </svg>Basic Info</h4>

    {{candidate.errors}}
    <div class="form-group row">
      <label class="col-sm-3 col-form-label required">First Name</span></label>

      <div class="col-sm-9">
        {{candidate.first_name |default_if_none:'____'}}
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Middle Name<span style="color:red;"></span></label>
      <div class="col-sm-9">
        {{candidate.middle_name |default_if_none:'____'}}
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Last Name<span style="color:red;"></span></label>
      <div class="col-sm-9">
        {{candidate.last_name |default_if_none:'____'}}
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Username<span style="color:red;"></span></label>
      <div class="col-sm-9">
        {{candidate.username |default_if_none:'____'}}
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Email Address<span style="color:red;"></span></label>
      <div class="col-sm-9">
        {{candidate.email |default_if_none:'____'}}
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Phone<span style="color:red;"></span></label>
      <div class="col-sm-9">
        {{candidate.mobile_number |default_if_none:'____'}}
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Address</label>
      <div class="col-sm-9">
        {{candidate.address |default_if_none:'____'}}
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Religion</label>
      <div class="col-sm-9">
        {{candidate.get_religion_display |default_if_none:'____'}}
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Gender<span style="color:red;"></span></label>
      <div class="col-sm-9">
        {{candidate.get_gender_display |default_if_none:'____'}}
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Nationality</label>
      <div class="col-sm-9">
        {{candidate.get_nationality_display |default_if_none:'____'}}
      </div>
    </div>
    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Date Of Birth<span style="color:red;"></span></label>
      <div class="col-sm-9">
        {{candidate.dob |default_if_none:'____'}}
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Marital Status</label>
      <div class="col-sm-9">
        {{candidate.get_marital_status_display| default_if_none:'____'}}
      </div>
    </div>

    <div class="form-group row">
      <label class="col-sm-3 col-form-label">Skills<span style="color:red;"></span></label>
      <div class="col-sm-9">
          <div class="skill-and-profile dashboard-section">
              <div class="skill">
                {% for skill in candidate.skills.all %}
                <a style="cursor:pointer;">{{skill}}</a>
                {% endfor %}
                <!-- Button trigger modal -->
              </div>
            </div>
      </div>
    </div>
  </div>
</div>


<div id="MyModal2" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content" id="update-modal-content">
    </div>
  </div>
</div>

{% endblock %}
{% comment %}
<!-- <form action="" method="post">
    {% csrf_token %}
    <div class="dashboard-section basic-info-input">
      <h4><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-lock"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path></svg>Change Password</h4>
      <div class="form-group row">
        <label class="col-sm-3 col-form-label">Current Password</label>
        <div class="col-sm-9">
          {{password.current_password}}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-3 col-form-label">New Password</label>
        <div class="col-sm-9">
          {{password.new_password}}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-3 col-form-label">Retype Password</label>
        <div class="col-sm-9">
          {{password.re_password}}
        </div>
      </div>
      <div class="form-group row">
        <label class="col-sm-3 col-form-label"></label>
        <div class="col-sm-9">
          <input type="submit" value="Save Changes" class="button btn-primary">
        </div>
      </div>
    </div>
  </form> -->





{% block script %}
<!-- Java Script for changing picture -->
<script>
  $("#inputGroupFile01").change(function (event) {
    RecurFadeIn();
    readURL(this);
  });
  $("#inputGroupFile01").on('click', function (event) {
    RecurFadeIn();
  });
  function readURL(input) {
    if (input.files && input.files[0]) {
      var reader = new FileReader();
      var filename = $("#inputGroupFile01").val();
      filename = filename.substring(filename.lastIndexOf('\\') + 1);
      reader.onload = function (e) {
        debugger;
        $('#blah').attr('src', e.target.result);
        $('#blah').hide();
        $('#blah').fadeIn(500);
        $('.custom-file-label').text(filename);
      }
      reader.readAsDataURL(input.files[0]);
    }
    $(".alert").removeClass("loading").hide();
  }
  function RecurFadeIn() {
    console.log('ran');
    FadeInAlert("Wait for it...");
  }
  function FadeInAlert(text) {
    $(".alert").show();
    $(".alert").text(text).addClass("loading");
  }
</script>
<!-- End Script for changing picture -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script src="{% static 'frontend/assets/js/jquery.datetimepicker.full.min.js'%}"></script>
<script>
  $('#id_dob').datetimepicker({
    format: 'Y-m-d',
    timepicker: false
  });
  $('#id_skills').select2({
    tags: true
  });

</script>

<script>
  $('.update-basic').click(function () {
    console.log('afkgseugfgerlhiughr')
    var that = this;
    $.ajax({
      method: 'GET',
      url: $(that).attr('data-url'),
      success: function (data) {
        $('#update-modal-content').html(data);
      }
    });
  });

  {% if basic_update_form.errors %}
  $('#MyModal').modal('show')
  {% endif %}

</script>
{% endblock %}

{% endcomment %}

frontend/templates/frontend/candidates/dashboard/statistics.html
{% extends 'candidate/dashboard/dashboard.html' %}
{% block title %}Dashboard{% endblock%}
{% block head %} {% endblock%}
{% load humanize %}

{% block dashboard %}
<div class="dashboard-content-wrapper">
<div class="dashboard-section user-statistic-block">
        <div class="user-statistic">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-pie-chart"><path d="M21.21 15.89A10 10 0 1 1 8 2.83"></path><path d="M22 12A10 10 0 0 0 12 2v10z"></path></svg>
          <h3>{{ jobs_viewed }}</h3>
          <span>Jobs Viewed</span>
        </div>
        <div class="user-statistic">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-briefcase"><rect x="2" y="7" width="20" height="14" rx="2" ry="2"></rect><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"></path></svg>
          <h3>{{applied_jobs}}</h3>
          <span>Applied Jobs</span>
        </div>
        <div class="user-statistic">
            <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-bookmark ">
              <path d="M19 21l-7-5-7 5V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2z"></path>
            </svg>
          <!-- <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-heart"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path></svg> -->
          <h3>{{bookmarked}}</h3>
          <span>Bookmarked Jobs</span>
        </div>
</div> 
  {% comment %}
      <div class="dashboard-section dashboard-view-chart"><iframe class="chartjs-hidden-iframe" tabindex="-1" style="display: block; overflow: hidden; border: 0px; margin: 0px; top: 0px; left: 0px; bottom: 0px; right: 0px; height: 100%; width: 100%; position: absolute; pointer-events: none; z-index: -1;"></iframe>
        <canvas id="view-chart" width="658" height="329" style="display: block; width: 658px; height: 329px;"></canvas>
      </div>
  {% endcomment %}
  
  
  <div class="dashboard-section dashboard-recent-activity">
        <h4 class="title">Recent Activity</h4>
        {% for c in candidate_activity %}
          <div class="activity-list">
            <i class="fas fa-bolt"></i>
            <a href="{{c.url }}"> 
            <div class="content">
              <h5>{{ c.activity }}  </h5>
              <span class="time">{{ c.created_at|naturaltime }}</span>
            </div> 
          </a>
          </div>
        {% endfor %}
      </div>
</div>
{% endblock %}