api/urls.py
from django.urls import path
from rest_framework.authtoken import views as drf_views

from . import views

urlpatterns = [
    path('token/', drf_views.obtain_auth_token),
    path('cv/', views.CVListAPIView.as_view()),
]

cv_generator/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('cvAdmin/', admin.site.urls),
    path('', include('frontend.urls')),
    path('dashboard/',include('dashboard.urls')),
    path('api/',include('api.urls')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/urls.py
from django.urls import path

from .views import *

app_name = 'frontend'

urlpatterns = [
    #HomeView
    path('', HomeView.as_view(), name='home'),

    #Accounts Login, Logout and Register
    path('login/', SigninView.as_view(), name='login'),
    path('logout/',LogoutView.as_view(), name = 'logout'),
    path('register/',SignupView.as_view(), name = 'signup'),

    #Email Confirmations 
    path('resend/token/', SendTokenView.as_view(), name = 'send_token'),
    path('activate/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/', activate, name='activate_account'),

    #Candidates Profile Detail updates
    path('candidate/<username>/', CandidateUpdateView.as_view(), name='candidate_update'),
    path('personaldetails/<int:pk>/', CandidateProfileDetailUpdateView.as_view(),  name='candidate_personal_detail_update'),
    
    # Candidate Photo Update
    path('candidate/photo/update/', CandidatePhotoUpdateView.as_view(), name='candidate_photo_update'),

    # Candidate CV Update and Download
    path('cv/edit/<username>/', CandidateEditCVTemplateView.as_view(), name='candidate_cv_update'),
    path('download/cv/', CandidateCVDownloadTemplateView.as_view(), name='candidate_cv_download'),
    # path('generate-cv/<int:pk>/', GenerateCVPDFView.as_view(), name="generate_cv_pdf"),

    # Candidate Education CRUD
    path('education/create/', CandidateEducationCreateView.as_view(), name='candidate_education_create'),
    path('education/<int:pk>/', CandidateEducationUpdateview.as_view(), name='candidate_education_update'),
    path('education/<int:pk>/delete/',CandidateEducationDeleteView.as_view(), name='candidate_education_delete'),
    path('aboutme/<int:pk>/', CandidateAboutMeUpdateView.as_view(), name='candidate_aboutme_update'),

    #Candidate Experience CRUD
    path('experience/<int:pk>/', CandidateExperienceUpdateView.as_view(),  name='candidate_experience_update'),
    path('experience/create/', CandidateExperienceCreateView.as_view(), name='candidate_experience_create'),
    path('experience/<int:pk>/delete/',CandidateExperienceDeleteView.as_view(), name = 'candidate_experience_delete'),


]

dashboard/models.py
from datetime import date, datetime
from urllib.parse import parse_qs, urlsplit

from django.apps import apps
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.core.validators import FileExtensionValidator
from django.db import models
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver
from django.shortcuts import get_object_or_404, reverse
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.html import strip_tags

from .utils import *
from .validators import *

GENDER = (
    (1,'Male'),
    (2,'Female'),
    (3,'Others'),
)


CURRENTLY_WORKING_TYPE = (
    ('Yes','Yes'),
    ('No','No'),
)

def get_candidate(user):
    try:
        return user.candidate
    except:
        pass
    return None


class DateTimeModel(models.Model):
    created_at = models.DateTimeField(
        auto_now_add=True,
        auto_now=False,
    )
    updated_at = models.DateTimeField(
        auto_now_add=False,
        auto_now=True,
    )
    deleted_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        abstract = True

    def delete(self):
        self.deleted_at = timezone.now()
        super().save()


class Skill(models.Model):
    name = models.CharField(max_length=254, unique=True)

    class Meta:
        ordering = ['-id']
        verbose_name = "Skill"
        verbose_name_plural = "Skills"

    def __str__(self):
        return self.name

class Candidate(User, DateTimeModel):
    gender = models.IntegerField(choices = GENDER,blank = False,null= True)
    dob = models.DateField(blank = False,null = True)
    is_verified = models.BooleanField(default = False)
    mobile_number = models.CharField(max_length=13,blank = False,null= True)
    address = models.CharField(max_length = 120,blank = False, null= True)
    skills = models.ManyToManyField(Skill,related_name='candidates')
    profile_image = models.FileField(null=True, blank=True, validators=[FileExtensionValidator(allowed_extensions=['png','jpg','jpeg'])])
    about_me = models.TextField(blank=True, null=True)
    
    class Meta:
        ordering = ['-id']
        verbose_name = "Candidate"
        verbose_name_plural = "Candidates"

    def __str__(self):
        return self.username

    @property
    def name(self):
        return "{0} {1} ".format(self.first_name,self.last_name)

    def get_photo(self):
        try:
            return self.profile_image.url
        except:
            return self.get_avatar()

    def get_avatar(self):
        url="https://ui-avatars.com/api/?background=0D8ABC&color=fff&name={0}+{1}&size=256".format(self.first_name,self.last_name)
        return url

    @property
    def get_skills(self):
        return self.skills.all

    @property
    def get_educations(self):
        return self.educational_qualifications.filter(deleted_at__isnull=True)


class EducationalQualification(DateTimeModel):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='educational_qualifications')
    degree = models.CharField(max_length=100)
    name_of_institute = models.CharField(max_length=200)
    university = models.CharField(max_length=200)
    location = models.CharField(max_length=100)
    started_year = models.CharField(max_length=10)
    passed_year = models.CharField(max_length=10)
    description = models.TextField()

    class Meta:
        verbose_name = "Educational Qualification"
        verbose_name_plural = "Educational Qualifications"
        ordering = ["-id"]

    def __str__(self):
        return self.candidate.username


class WorkExperience(DateTimeModel):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='work_experiences')
    job_title = models.CharField(max_length=250)
    organization = models.CharField(max_length=250)
    is_working = models.IntegerField(choices=CURRENTLY_WORKING_TYPE , null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    job_description = models.TextField(null=True, blank=True)

    class Meta:
        verbose_name = "Work Experience"
        verbose_name_plural = "Work Experiences"
        ordering = ["-id"]

    def __str__(self):
        return self.candidate.username

    
class CurriculumVitae(DateTimeModel):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE, related_name='cvs')
    cv_generated = models.FileField()

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.candidate.username

frontend/models.py
from django.db import models

# Create your models here.

frontend/views.py
from collections import OrderedDict
from io import BytesIO

from django.core.files import File
from django.core.mail import send_mail
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils.encoding import force_bytes, force_text
from django.views.generic import View, TemplateView, FormView, CreateView, UpdateView, DeleteView
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import get_template
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from frontend.tasks import send_verification_email

from .mixins import *
from dashboard.models import * 
from .forms import *
from .tokens import account_activation_token
from .utils import render_to_pdf


#HomeView
class HomeView(TemplateView):
    template_name = 'frontend/layouts/home.html'

#Account Login View
class SigninView(FormView):        
    form_class =  SigninForm
    model = User    
    template_name = 'frontend/auth/login.html'
    success_url = reverse_lazy('frontend:home')

    def form_valid(self, form):
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        candidate = get_candidate(user)
        if user:
            if user.is_active and candidate is not None:
                if candidate.is_verified: 
                    login(self.request, user)
                    if self.request.GET.get('to') == 'profile':
                        return redirect('frontend:candidate_update',kwargs={'username':candidate.username})
                    else:
                        return render(self.request,'frontend/auth/login.html',{'message':'Please Check your email inbox for activation email','form':SigninForm})
        else:
            return render(self.request,'frontend/auth/login.html',{'message':'Please Check your username and password again and try to login','form':SigninForm})

    def form_invalid(self, form):
        if form.errors:
            return render(self.request, self.template_name,{"form":SigninForm, "errors":form.errors})
        return super().form_invalid(form)


#Account Logout View
class LogoutView(View):

    def get(self, request,*args,**kwargs):
        logout(request)
        return redirect('frontend:home')


#Account Register View
class SignupView(CreateView):
    form_class = CandidateSignupForm
    template_name = "frontend/auth/register.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['candidate_registration_form'] = context['form']
        return context

    def get_success_url(self):
        return render(self.request,'frontend/layouts/home.html', {'message':'Please Check your email inbox for activation email'})
    
    def form_valid(self,form):
        username = form.cleaned_data['username']
        password1 = form.cleaned_data['password1']
        form.instance.set_password(password1)
        user = form.save(commit=False)
        user.is_active = True
        user.save()
        
        user = authenticate(self.request,username = username, password = password1)
        login(self.request,user,backend='django.contrib.auth.backends.ModelBackend')
        send_verification_email.delay(user_pk=user.pk)
        return render(self.request,'frontend/layouts/home.html', {'message':'Please Check your email inbox for activation email'})

    def form_invalid(self,form):
        if form.errors:
            return render(self.request, self.template_name, {"candidate_registration_form":CandidateSignupForm,'errors':form.errors})
        else:
            return super().form_invalid(form)



#Send token for account activation
class SendTokenView(View):
    def get(self, request, *args, **kwargs):
        send_verification_email.delay(user_pk=request.user.pk)
        return redirect('frontend:email_confirmation')
        


#Activation of account via activation email
def activate(request, uidb64, token):

    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)

    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        return render(request,'frontend/layouts/home.html', {'message':'Please Check your email inbox for activation email'})
    if user.is_authenticated:
        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            if get_candidate(user):
                user.candidate.is_verified = True
                user.candidate.save()            
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')           
                messages.success(request, 'Account Activation Successful!')            
                return redirect('frontend:candidate_update', kwargs={'username':user.username})
        else:
            return render(request, 'frontend/layouts/home.html', {'message':'Please Check your email inbox for activation email'})
    else:
        return render(request,'frontend/layouts/home.html',  {'message':'Please Check your email inbox for activation email'})



#Candidates Update View
class CandidateUpdateView(CandidateRequired403Mixin, UpdateView):
    model = Candidate
    template_name = 'frontend/candidates/profile_edit.html'
    form_class = CandidateCreateForm

    def get_object(self, *args, **kwargs):
        candidate = get_candidate(self.request.user)
        return candidate

    def get_success_url(self):
        return reverse_lazy('frontend:candidate_update',kwargs={'username':self.kwargs.get('username')})

    def form_invalid(self,form):
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return super().form_invalid(form)

    def form_valid(self,form):
        response = super().form_valid(form)
        if self.request.is_ajax():
            return JsonResponse({'status':'ok'}, status=200)
        else:
            return response


#Candidates Photo Update View
class CandidatePhotoUpdateView(CandidateRequired403Mixin,CandidateRedirectMixin, UpdateView):
    template_name = 'frontend/candidates/candidate_photo_update.html'
    form_class = CandidatePhotoUpdateForm
    model = Candidate

    def get_object(self, *args, **kwargs):
        instance = get_candidate(self.request.user)
        return instance

    def get_success_url(self,*args,**kwargs):
          return reverse_lazy('frontend:candidate_cv_update',kwargs={'username':self.request.user.username})

    def form_valid(self, form):
        response = super().form_valid(form)

        if self.request.is_ajax():
            return JsonResponse({}, status=200)
        return response
    
    def form_invalid(self, form):
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        return super().form_invalid(form)


#Candidates Profile Detail Update View
class CandidateProfileDetailUpdateView(CandidateRequired403Mixin, GetCandidateMixin, CandidateRedirectMixin, UpdateView):
    model = Candidate
    form_class = CandidateProfileDetailCreateForm
    template_name = 'frontend/candidates/personal_detail_edit.html'

    def get_context_data(self, *args, **kwargs):
        context =  super().get_context_data(*args, **kwargs)
        context['url'] = reverse_lazy('frontend:candidate_personal_detail_update', kwargs={'pk':self.get_object().pk})
        return context

    def form_valid(self, form):
        print(form.data,32374902374)
        user = get_object_or_404(User,username=self.request.user.username)
        user.first_name = form.cleaned_data.get('first_name')
        user.last_name = form.cleaned_data.get('last_name')
        user.save()
        form.save()
        response = super().form_valid(form)
        if self.request.is_ajax():
            return JsonResponse({}, status=200)
        return response

    def form_invalid(self, form):
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        return super().form_invalid(form)


#Candidate can edit their CV Templates
class CandidateEditCVTemplateView(CandidateRequired403Mixin, GetCandidateMixin, TemplateView):
    template_name = 'frontend/candidates/edit_cv.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['image_form'] = CandidatePhotoUpdateForm()
        return context


#Candidate can download their CV in their desired format
class CandidateCVDownloadTemplateView(CandidateRequired403Mixin, TemplateView):
    template_name = 'frontend/cvs/cv1.html'

    def get(self, request, *args, **kwargs):
        response = super().get(request, *args, **kwargs)
        candidate = get_candidate(self.request.user)
        templates = OrderedDict()
        templates['1'] = 'cv1.html'
        
        samples = OrderedDict()
        samples['1'] = 'sample1.png'

        sample_id = request.GET.get('sample')
        template = templates.get(sample_id, 'cv1.html')
        self.template_name = 'frontend/cvs/' + template
        context = {'candidate': candidate}
        pdf = render_to_pdf(self.template_name, context)
        filename = "{}-cv.pdf".format(candidate.username)
        cv_obj = CurriculumVitae.objects.create(candidate=candidate)
        cv_obj.cv_generated.save(filename, File(BytesIO(pdf.content)))
        return render(request, self.template_name, context={'candidate':candidate, 'samples':samples, 'templates':templates})


class CandidateCompleteProfileUpdateView(CandidateRequired403Mixin,UpdateView):
    model = Candidate
    template_name = 'frontend/candidates/dashboard/profile_edit.html'
    form_class = CandidateProfileCompleteForm
    
    def get_success_url(self):

frontend/templates/frontend/candidates/detail.html
{% extends 'layouts/base.html' %}

{% block title %}{{ candidate.name }}{% endblock %}

{% block content %}
<!-- Candidates Details -->
<div class="alice-bg padding-top-60 section-padding-bottom">
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="candidate-details">
                    <div class="title-and-info">
                        <div class="title">

                            <div class="thumb">
                                {% if candidate.profile_image %}
                                <img src="{{ candidate.profile_image.url }}" class="img-fluid" alt="">
                                {% else %}
                                <img src="" class="img-fluid" alt="">
                                {% endif %}
                            </div>
                            <div class="title-body">
                                <h4>{{ candidate.name }}</h4>
                                <div class="info">
                                    <span class="candidate-designation"><i data-feather="check-square"></i>ios
                                        Developer</span>
                                    <span class="candidate-location"><i
                                            data-feather="map-pin"></i>{{ candidate.address }}</span>
                                </div>
                            </div>
                        </div>
                        <div class="download-cv">
                            <a href="#">Download CV <i data-feather="download"></i></a>
                        </div>
                    </div>
                    <div class="skill-and-profile">
                        <div class="skill">
                            <label>Skills:</label>
                            {% if candidate.get_skills %}
                            {% for skill in candidate.get_skills %}
                            <a href="#">{{ skill }}</a>
                            {% endfor %}
                            {% endif %}
                        </div>
                        <div class="social-profile">
                            <label>Social:</label>
                            {% if candidate.socialaccounts.all %}
                            {% for account in candidate.socialaccounts.all %}
                            <a href="{{ account.links }}"><i class="fab fa-facebook-f"></i></a>
                            {% endfor %}
                            {% endif %}
                        </div>
                    </div>
                    <div class="details-information section-padding-60">
                        <div class="row">
                            <div class="col-xl-7 col-lg-8">
                                <div class="about-details details-section">
                                    <h4><i data-feather="align-left"></i>About Me</h4>
                                    {{ candidate.about_me|safe }}
                                </div>
                                <div class="edication-background details-section">
                                    <h4><i data-feather="book"></i>Education Background</h4>
                                    {% if candidate.educations.all %}
                                    {% for education in candidate.educations.all %}
                                    <div class="education-label">
                                        <span class="study-year">{{ education.graduation_year }}</span>
                                        <h5>{{ education.get_degree_display }}<span>@
                                                {{ education.name_of_institute }}</span></h5>
                                    </div>
                                    {% endfor %}
                                    {% endif %}

                                </div>
                                <div class="experience details-section">
                                    <h4><i data-feather="briefcase"></i>Work Experiance</h4>
                                    {% if candidate.experiences.all %}
                                    {% for experience in candidate.experiences.all %}
                                    <div class="experience-section">
                                        <span class="service-year">{{ experience.start_date }} -
                                            {{ experience.end_date }}</span>
                                        <h5>{{ experience.job_title }}<span>@ {{ experience.organization_name }}</span></h5>
                                        <p>
                                            {{ experience.duties_responsibilities|safe }}
                                        </p>
                                    </div>
                                    {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="professonal-skill details-section">
                                    <h4><i data-feather="feather"></i>Professional Skill</h4>
                                    <p>Combined with a handful of model sentence structures, to generate lorem Ipsum
                                        which It has survived not only five centuries, but also the leap into electronic
                                        typesetting</p>
                                    <div class="progress-group">
                                        <div class="progress-item">
                                            <div class="progress-head">
                                                <p class="progress-on">Photoshop</p>
                                            </div>
                                            <div class="progress-body">
                                                <div class="progress">
                                                    <div class="progress-bar" role="progressbar" aria-valuenow="70"
                                                        aria-valuemin="0" aria-valuemax="100" style="width: 0;"></div>
                                                </div>
                                                <p class="progress-to">70%</p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="special-qualification details-section">
                                    <h4><i data-feather="gift"></i>Special Qualification</h4>
                                    <ul>
                                        <li>5 years+ experience designing and building products.</li>
                                        <li>Skilled at any Kind Design Tools.</li>
                                        <li>Passion for people-centered design, solid intuition.</li>
                                        <li>Hard Worker & Quick Lerner.</li>
                                    </ul>
                                </div>
                                <div class="portfolio details-section">
                                    <h4><i data-feather="gift"></i>Portfolio</h4>
                                    <div class="portfolio-slider owl-carousel">
                                        {% if candidate.portfolios.all %}
                                        {% for portfolio in candidate.portfolios.all %}
                                        <div class="portfolio-item">
                                            <img src="{{ portfolio.document.url }}" class="img-fluid" alt="">
                                            <div class="overlay">
                                                <a href="{{ portfolio.document.url }}" target="_blank"><i
                                                        data-feather="eye"></i></a>
                                                <a href="#"><i data-feather="link"></i></a>
                                            </div>
                                        </div>
                                        {% endfor %}
                                        {% else %}
                                        <div class="portfolio-item">
                                        </div>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                            <div class="col-xl-4 offset-xl-1 col-lg-4">
                                <div class="information-and-contact">
                                    <div class="information">
                                        <h4>Information</h4>
                                        <ul>
                                            <li><span>Category:</span> {{ candidate.preferences.first.specializations }}
                                            </li>
                                            <li><span>Location:</span> {{ candidate.address }}</li>
                                            <li><span>Gender:</span> {{ candidate.get_gender_display }}</li>
                                            <li><span>Age:</span> {{ candidate.get_age }} Year(s)</li>
                                            <li><span>Qualification:</span>
                                                {{ candidate.educations.first.get_degree_display }}</li>
                                        </ul>
                                    </div>
                                    <div class="buttons">
                                        <a href="#" class="button contact-button" data-toggle="modal"
                                            data-target="#exampleModal">Contact Me</a>
                                        <a href="#" class="button cover-download"><i data-feather="download"></i>Cover
                                            Letter</a>
                                        <a href="#" class="button contact-download"><i
                                                data-feather="download"></i>Contact</a>
                                    </div>
                                    <!-- Modal -->
                                    <div class="modal fade contact-form-modal" id="exampleModal" tabindex="-1"
                                        role="dialog" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-body">
                                                    <h4><i data-feather="edit"></i>Contact Me</h4>
                                                    <form action="#">
                                                        <div class="form-group">
                                                            <input type="text" class="form-control"
                                                                placeholder="Your Name">
                                                        </div>
                                                        <div class="form-group">
                                                            <input type="email" class="form-control"
                                                                placeholder="Your Email">
                                                        </div>
                                                        <div class="form-group">
                                                            <textarea class="form-control"
                                                                placeholder="Your Message"></textarea>
                                                        </div>
                                                        <button class="button">Submit</button>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xl-7 col-lg-8">
                            <div class="personal-information details-section">
                                <h4><i data-feather="user-plus"></i>Personal Deatils</h4>
                                <ul>
                                    <li><span>Full Name:</span> {{ candidate.name }}</li>
                                    <li><span>Date of Birth:</span> {{ candidate.dob }}</li>
                                    <!-- <li><span>Nationality:</span> American </li> -->
                                    <li><span>Sex:</span> {{ candidate.get_gender_display }}</li>
                                    <li><span>Address:</span> {{ candidate.address }}</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Candidates Details End -->
{% endblock %}